#!/usr/bin/env python3
"""
update_progress.py — 根据 check_stage 结果自动重写 <project>/PROGRESS.md

Usage:
  scripts/update_progress.py <project>
  scripts/update_progress.py hermes

规则：
  - 遍历 <project>/stages/XX-*/ 所有阶段
  - 对每个阶段跑 check_stage，得到 PASS/FAIL/EMPTY 状态
  - 根据结果确定状态图标：
    ✅ 完成 = 全部产出满足
    🔄 进行中 = 部分产出满足（1 <= passed < total）
    ⏳ 待开始 = 无产出或未创建 deliverables.yaml
  - 重写 PROGRESS.md 的"阶段进度"表格
  - 保留"变更记录"区块不动
  - 在顶部加"自动生成"警告注释
"""
from __future__ import annotations

import sys
import re
import tempfile
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from check_stage import check_stage  # noqa: E402


STAGE_NAMES = {
    "01-requirements": "Requirements（需求分析）",
    "02-system-design": "System Design（系统设计）",
    "03-module-design": "Module Design（模块接口设计）",
    "04-development": "Development（TDD 开发）",
    "05-testing": "Testing（测试验证）",
    "06-deployment": "Deployment（上线部署）",
    "07-operations": "Operations（监控运维）",
}


def determine_stage_status(report: dict) -> tuple[str, str]:
    """Return (icon_status, human_label) based on check report."""
    if report["status"] == "PASS":
        return "✅ 完成", "done"
    if report["status"] == "NO_MANIFEST":
        return "⏳ 待开始", "pending"
    if report["status"] == "EMPTY":
        return "⏳ 待开始", "pending"
    # FAIL
    if report["passed"] == 0:
        return "⏳ 待开始", "pending"
    return f"🔄 进行中 ({report['passed']}/{report['total']})", "in_progress"


def find_current_stage(stages: list[tuple[str, dict]]) -> str | None:
    """Find the first non-done stage. That's the current stage."""
    for stage_id, report in stages:
        if report["status"] != "PASS":
            return stage_id
    return None


def build_progress_content(project: str, stages: list[tuple[str, dict]], preserved_changelog: str) -> str:
    current_stage = find_current_stage(stages)
    current_label = STAGE_NAMES.get(current_stage, current_stage) if current_stage else "全部完成"

    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"<!-- Auto-generated by scripts/update_progress.py at {ts}. Edits to the '阶段进度' table will be overwritten. -->",
        "",
        f"# {project.capitalize()} 项目进度",
        "",
        "## 当前状态",
        "",
        f"- **阶段**：{current_label}",
        "",
        "## 阶段进度",
        "",
        "| 阶段 | 名称 | 状态 | 产出进度 |",
        "|------|------|------|---------|",
    ]

    for stage_id, report in stages:
        stage_num = stage_id.split("-")[0]
        name = STAGE_NAMES.get(stage_id, report.get("name", stage_id))
        status_label, _ = determine_stage_status(report)
        if report["status"] == "NO_MANIFEST":
            progress = "无清单"
        else:
            progress = f"{report['passed']}/{report['total']}"
        lines.append(f"| {stage_num} | {name} | {status_label} | {progress} |")

    lines.append("")
    lines.append("## 产出明细")
    lines.append("")
    for stage_id, report in stages:
        if report["status"] == "NO_MANIFEST":
            continue
        lines.append(f"### {stage_id}")
        lines.append("")
        for r in report["results"]:
            icon = "✓" if r["ok"] else "✗"
            lines.append(f"- {icon} `{r['id']}` — {r['message']}")
        lines.append("")

    if preserved_changelog:
        lines.append(preserved_changelog.rstrip())
        lines.append("")
    else:
        lines.append("## 变更记录")
        lines.append("")
        lines.append("| 日期 | 变更内容 |")
        lines.append("|------|---------|")
        lines.append("")

    return "\n".join(lines)


def extract_changelog(existing: str) -> str:
    """Extract the '变更记录' section from existing PROGRESS.md so we preserve manual notes."""
    match = re.search(r"(## 变更记录.*?)(?=\n## |\Z)", existing, re.DOTALL)
    if match:
        return match.group(1)
    return ""


def update_progress(project: str) -> int:
    project_dir = REPO_ROOT / project
    stages_dir = project_dir / "stages"
    if not stages_dir.exists():
        print(f"ERROR: {stages_dir} does not exist", file=sys.stderr)
        return 2

    stage_ids = sorted(p.name for p in stages_dir.iterdir() if p.is_dir())

    reports = []
    for stage_id in stage_ids:
        report = check_stage(project, stage_id)
        reports.append((stage_id, report))

    progress_file = project_dir / "PROGRESS.md"
    existing = progress_file.read_text(encoding="utf-8") if progress_file.exists() else ""
    preserved = extract_changelog(existing)

    content = build_progress_content(project, reports, preserved)

    # Atomic write: write to temp file first, then rename
    tmp_fd, tmp_path = tempfile.mkstemp(
        dir=str(progress_file.parent), suffix=".tmp", prefix=".progress_"
    )
    try:
        with open(tmp_fd, "w", encoding="utf-8") as f:
            f.write(content)
        Path(tmp_path).replace(progress_file)
    except Exception:
        Path(tmp_path).unlink(missing_ok=True)
        raise

    print(f"✅ Updated {progress_file.relative_to(REPO_ROOT)}")
    for stage_id, report in reports:
        status_label, _ = determine_stage_status(report)
        print(f"   {stage_id}: {status_label}")

    return 0


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    project = sys.argv[1]
    return update_progress(project)


if __name__ == "__main__":
    sys.exit(main())
